export const DEMO_COMMERCE_FIXTURES = Object.freeze([
  Object.freeze({
    id: "demo-fixture-camel-chore-jacket",
    title: "Camel Chore Jacket",
    description: "Structured cotton canvas with utility patch pockets.",
    imageUrl: "/demo/shopify/camel-chore-jacket.svg",
    imageAlt: "Camel chore jacket commerce preview",
    price: "89",
    currencyCode: "USD",
    available: true,
    source: "demo-fixture",
  }),
  Object.freeze({
    id: "demo-fixture-camel-work-jacket",
    title: "Camel Work Jacket",
    description: "A warmer workwear layer with a clean, everyday shape.",
    imageUrl: "/demo/shopify/camel-work-jacket.svg",
    imageAlt: "Camel work jacket commerce preview",
    price: "105",
    currencyCode: "USD",
    available: true,
    source: "demo-fixture",
  }),
  Object.freeze({
    id: "demo-fixture-sand-overshirt",
    title: "Sand Overshirt",
    description: "A lightweight neutral layer for smart-casual combinations.",
    imageUrl: "/demo/shopify/sand-overshirt.svg",
    imageAlt: "Sand overshirt commerce preview",
    price: "79",
    currencyCode: "USD",
    available: true,
    source: "demo-fixture",
  }),
]);
